# Generated by Django 4.1 on 2023-04-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eplayhere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
