# Generated by Django 4.1 on 2023-04-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eplayhere', '0002_alter_projectdetails_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='technology_used',
            field=models.CharField(max_length=500),
        ),
    ]
