# Generated by Django 4.1 on 2023-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('phone', models.TextField(max_length=16)),
                ('email', models.EmailField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
    ]
