# Generated by Django 4.1 on 2023-02-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('points', models.IntegerField()),
                ('category', models.TextField(max_length=50)),
                ('gamename', models.TextField(max_length=100)),
            ],
        ),
    ]
