# Generated by Django 4.1 on 2023-02-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpoints',
            name='category',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='allpoints',
            name='gamename',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
