# Generated by Django 4.1 on 2023-02-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_allpoints_category_alter_allpoints_gamename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpoints',
            name='points',
            field=models.FloatField(),
        ),
    ]
