# Generated by Django 4.1 on 2023-02-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_allpoints_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpoints',
            name='timetaken',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
