# Generated by Django 4.1 on 2022-11-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mes', models.TextField()),
            ],
        ),
    ]
