# Generated by Django 4.1 on 2023-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeriF',
            fields=[
                ('user_name', models.TextField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True)),
                ('upload_chart', models.FileField(default=None, max_length=250, null=True, upload_to='certificate/')),
            ],
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(upload_to='certificatefiles/')),
                ('mainlogo', models.FileField(upload_to='certificatefiles/')),
                ('namefont', models.FileField(upload_to='certificatefiles/')),
                ('ph', models.FileField(upload_to='certificatefiles/')),
                ('phlogo', models.FileField(upload_to='certificatefiles/')),
                ('textfont', models.FileField(upload_to='certificatefiles/')),
            ],
        ),
    ]
