# Generated by Django 4.1 on 2023-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='output',
            field=models.FileField(default='', upload_to='certificatefiles/'),
            preserve_default=False,
        ),
    ]
