# Generated by Django 4.1 on 2023-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificateDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=250, null=True)),
                ('exm_date', models.DateField(blank=True, null=True)),
                ('created_dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='certificateStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_bg', models.FileField(blank=True, null=True, upload_to='certificateApi/bg/')),
                ('c_main_logo', models.FileField(blank=True, null=True, upload_to='certificateApi/mainlogo/')),
                ('c_logo', models.FileField(blank=True, null=True, upload_to='certificateApi/logo/')),
                ('c_font_1', models.FileField(upload_to='certificateApi/font1/')),
                ('c_font_2', models.FileField(upload_to='certificateApi/font2/')),
                ('c_ceo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_cto_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
