# Generated by Django 4.1 on 2023-04-27 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatedynamic',
            name='output_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificateApi/outputCertificate/'),
        ),
        migrations.AddField(
            model_name='certificatedynamic',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
