# Generated by Django 4.1 on 2022-10-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_profile_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mostplayed',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recent_cat',
        ),
    ]
