# Generated by Django 4.1 on 2022-10-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_mostplayed_profile_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_game_played',
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
