# Generated by Django 4.1 on 2022-10-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_profile_rank_remove_profile_total_game_played_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.TextField()),
                ('c_bio', models.TextField()),
                ('bg_image', models.TextField(blank=True)),
            ],
        ),
    ]
