# Generated by Django 4.1 on 2022-10-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_questions_category_questions_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timetkaen',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
    ]
