# Generated by Django 4.1 on 2022-10-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_profile_timetkaen'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='subquestion',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
