# Generated by Django 4.1 on 2022-11-08 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_alter_profile_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(null=True, upload_to='profile')),
                ('mobile_number', models.PositiveBigIntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('zip_code', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=225, null=True)),
                ('website', models.URLField(max_length=100, null=True)),
                ('bio', models.CharField(max_length=225, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
