# Generated by Django 4.1 on 2022-11-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_addmore_address_alter_addmore_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmore',
            name='website',
        ),
    ]
